<a href="https://colab.research.google.com/github/theritik08/Machine-Learning/blob/main/Working_with_APIs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **API(Application Programming Interface)**
Application Programming Interface, is a set of rules that allows different software applications to communicate and exchange data with each other. It acts as a digital middleman, delivering a request from one system to another and bringing the response back

**TMDB API(TOP RATED MOVIES)**

In [1]:
import pandas as pd
import requests

In [4]:
response=requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=fab97f3edabaf2d64d83d65ef5dc35e0&language=en-US&page=1')

* **<Response[200]>**:means Everything Fine
* **<Response[404]>**:data not available
* **<Response[500]>**:server down

In [17]:
#To explicitly convert the data to JSON Formate
#when you write result you get particular secion result from json
response.json()['results']

[{'adult': False,
  'backdrop_path': '/iCML6fBe3X0y06P33bM7dyYXPKZ.jpg',
  'genre_ids': [35, 10749],
  'id': 1632181,
  'title': 'Accidental Partners',
  'original_language': 'es',
  'original_title': 'Socias por accidente',
  'overview': 'Two women discover they were both scammed by the same man (who also got them pregnant). They form an alliance to take revenge.',
  'popularity': 21.6787,
  'poster_path': '/sr1Yoj6XLPTWYcbDoBy67xivW4I.jpg',
  'release_date': '2026-03-12',
  'softcore': False,
  'video': False,
  'vote_average': 9.066,
  'vote_count': 304},
 {'adult': False,
  'backdrop_path': '/zMwhWailP1WY7sb6AoE6b8ugoy.jpg',
  'genre_ids': [12, 16, 10751, 14],
  'id': 1007757,
  'title': 'Swapped',
  'original_language': 'en',
  'original_title': 'Swapped',
  'overview': 'A small woodland creature and a majestic bird, two natural sworn enemies of the Valley, magically trade places and set off on an adventure of a lifetime to switch back. Their journey soon uncovers a greater threat—one that could endanger not only their species, but the entire valley they call home.',
  'popularity': 88.4108,
  'poster_path': '/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg',
  'release_date': '2026-05-01',
  'softcore': False,
  'video': False,
  'vote_average': 8.915,
  'vote_count': 1923},
 {'adult': False,
  'backdrop_path': '/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg',
  'genre_ids': [18, 80],
  'id': 278,
  'title': 'The Shawshank Redemption',
  'original_language': 'en',
  'original_title': 'The Shawshank Redemption',
  'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
  'popularity': 167.41,
  'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
  'release_date': '1994-09-23',
  'softcore': False,
  'video': False,
  'vote_average': 8.725,
  'vote_count': 30748},
 {'adult': False,
  'backdrop_path': '/ufSwlnECLoUbBjPrFqEQcWBzHwc.jpg',
  'genre_ids': [10402, 18],
  'id': 936075,
  'title': 'Michael',
  'original_language': 'en',
  'original_title': 'Michael',
  'overview': 'The story of Michael Jackson, one of the most influential artists the world has ever known, and his life beyond the music. His journey from the discovery of his extraordinary talent as the lead of the Jackson Five, to the visionary artist whose creative ambition fueled a relentless pursuit to become the biggest entertainer in the world, highlighting both his life off-stage and some of the most iconic performances from his early solo career.',
  'popularity': 175.7718,
  'poster_path': '/zm0KAbOjlt9eR5y7vDiL2dEOwMl.jpg',
  'release_date': '2026-04-22',
  'softcore': False,
  'video': False,
  'vote_average': 8.701,
  'vote_count': 3458},
 {'adult': False,
  'backdrop_path': '/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg',
  'genre_ids': [18, 80],
  'id': 238,
  'title': 'The Godfather',
  'original_language': 'en',
  'original_title': 'The Godfather',
  'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
  'popularity': 38.3895,
  'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
  'release_date': '1972-03-14',
  'softcore': False,
  'video': False,
  'vote_average': 8.687,
  'vote_count': 23153},
 {'adult': False,
  'backdrop_path': '/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg',
  'genre_ids': [878, 12],
  'id': 687163,
  'title': 'Project Hail Mary',
  'original_language': 'en',
  'original_title': 'Project Hail Mary',
  'overview': 'Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction.',
  'popularity': 163.4379,
  'poster_path': '/yihdXomYb5kTeSivtFndMy5iDmf.jpg',
  'release_date': '2026-03-15',
  'softcore': False,
  'video': False,
  'vote_average': 8.67,
  'vote_count': 5994},
 {'adult': False,
  'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
  'genre_ids': [18, 80],
  'id': 240,
  'title': 'The Godfather Part II',
  'original_language': 'en',
  'original_title': 'The Godfather Part II',
  'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
  'popularity': 33.3141,
  'poster_path': '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
  'release_date': '1974-12-20',
  'softcore': False,
  'video': False,
  'vote_average': 8.571,
  'vote_count': 14037},
 {'adult': False,
  'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
  'genre_ids': [18, 36, 10752],
  'id': 424,
  'title': "Schindler's List",
  'original_language': 'en',
  'original_title': "Schindler's List",
  'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
  'popularity': 22.1871,
  'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
  'release_date': '1993-12-15',
  'softcore': False,
  'video': False,
  'vote_average': 8.57,
  'vote_count': 17592},
 {'adult': False,
  'backdrop_path': '/qqHQsStV6exghCM7zbObuYBiYxw.jpg',
  'genre_ids': [18],
  'id': 389,
  'title': '12 Angry Men',
  'original_language': 'en',
  'original_title': '12 Angry Men',
  'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
  'popularity': 22.4873,
  'poster_path': '/zhG3vKWyDRaZYoaww1UVAi29T9h.jpg',
  'release_date': '1957-04-10',
  'softcore': False,
  'video': False,
  'vote_average': 8.565,
  'vote_count': 10110},
 {'adult': False,
  'backdrop_path': '/bVGHSe47W6oCQL1Q88pvRAet51A.jpg',
  'genre_ids': [18, 9648],
  'id': 1330021,
  'title': 'Remarkably Bright Creatures',
  'original_language': 'en',
  'original_title': 'Remarkably Bright Creatures',
  'overview': 'Through unlikely bonds formed during night shifts at a local aquarium, Tova, an elderly widow, learns of a life-changing discovery that may bring her joy and wonder once again.',
  'popularity': 22.6466,
  'poster_path': '/9HcEqn3D4J6b2Z0jK54id9nA0fr.jpg',
  'release_date': '2026-05-07',
  'softcore': False,
  'video': False,
  'vote_average': 8.551,
  'vote_count': 722},
 {'adult': False,
  'backdrop_path': '/vpuPY4UziUCxv7gYYoaZQ3LX7to.jpg',
  'genre_ids': [28, 53],
  'id': 1383731,
  'title': 'Protector',
  'original_language': 'en',
  'original_title': 'Protector',
  'overview': "Nikki's life is shattered when her daughter is kidnapped. Thrust into the criminal underworld while hunted by cops and military, she must fight to rescue her child.",
  'popularity': 19.0537,
  'poster_path': '/icOZpnGuH9YrEaW3wrw5GJaXGih.jpg',
  'release_date': '2026-02-20',
  'softcore': False,
  'video': False,
  'vote_average': 8.5,
  'vote_count': 423},
 {'adult': False,
  'backdrop_path': '/dyJvKsNs2KP8qQnAXbRwDjblViy.jpg',
  'genre_ids': [16, 10751, 14],
  'id': 129,
  'title': 'Spirited Away',
  'original_language': 'ja',
  'original_title': '千と千尋の神隠し',
  'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
  'popularity': 36.5499,
  'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
  'release_date': '2001-07-20',
  'softcore': False,
  'video': False,
  'vote_average': 8.535,
  'vote_count': 18526},
 {'adult': False,
  'backdrop_path': '/dqK9Hag1054tghRQSqLSfrkvQnA.jpg',
  'genre_ids': [28, 80, 53],
  'id': 155,
  'title': 'The Dark Knight',
  'original_language': 'en',
  'original_title': 'The Dark Knight',
  'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
  'popularity': 42.6872,
  'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
  'release_date': '2008-07-16',
  'softcore': False,
  'video': False,
  'vote_average': 8.532,
  'vote_count': 36080},
 {'adult': False,
  'backdrop_path': '/84beTJf26mfhoasUlKSOiNSutyS.jpg',
  'genre_ids': [35, 18, 10749],
  'id': 19404,
  'title': 'Dilwale Dulhania Le Jayenge',
  'original_language': 'hi',
  'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
  'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
  'popularity': 12.2635,
  'poster_path': '/tFbfCkS7q6g96wVoAu8kyr93iPm.jpg',
  'release_date': '1995-10-20',
  'softcore': False,
  'video': False,
  'vote_average': 8.51,
  'vote_count': 4600},
 {'adult': False,
  'backdrop_path': '/b6HWTOxn1xevvyHU2K9ICvaRU6g.jpg',
  'genre_ids': [14, 18, 80],
  'id': 497,
  'title': 'The Green Mile',
  'original_language': 'en',
  'original_title': 'The Green Mile',
  'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
  'popularity': 26.8308,
  'poster_path': '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
  'release_date': '1999-12-10',
  'softcore': False,
  'video': False,
  'vote_average': 8.506,
  'vote_count': 19422},
 {'adult': False,
  'backdrop_path': '/xyWKrni8WrYzqn7ztvI5nIY0h62.jpg',
  'genre_ids': [35, 10749],
  'id': 1181678,
  'title': '¿Quieres ser mi hijo?',
  'original_language': 'en',
  'original_title': '¿Quieres ser mi hijo?',
  'overview': 'Lu, a conformist woman in her forties, learns that her 15-year partner has been having extramarital affairs. Starting from scratch, she gets involved in an unexpected relationship with a young womanizer.',
  'popularity': 9.843,
  'poster_path': '/6PQJsmuvSMZQMmlJfTpjIkrizUh.jpg',
  'release_date': '2023-09-21',
  'softcore': False,
  'video': False,
  'vote_average': 8.501,
  'vote_count': 356},
 {'adult': False,
  'backdrop_path': '/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg',
  'genre_ids': [12, 14, 28],
  'id': 122,
  'title': 'The Lord of the Rings: The Return of the King',
  'original_language': 'en',
  'original_title': 'The Lord of the Rings: The Return of the King',
  'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b',
  'popularity': 36.8675,
  'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
  'release_date': '2003-12-17',
  'softcore': False,
  'video': False,
  'vote_average': 8.5,
  'vote_count': 26827},
 {'adult': False,
  'backdrop_path': '/wCuUKiRaz0wEESsYqmQy005xvTE.jpg',
  'genre_ids': [35, 53, 18],
  'id': 496243,
  'title': 'Parasite',
  'original_language': 'ko',
  'original_title': '기생충',
  'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
  'popularity': 28.2785,
  'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
  'release_date': '2019-05-30',
  'softcore': False,
  'video': False,
  'vote_average': 8.492,
  'vote_count': 20854},
 {'adult': False,
  'backdrop_path': '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
  'genre_ids': [53, 80, 35],
  'id': 680,
  'title': 'Pulp Fiction',
  'original_language': 'en',
  'original_title': 'Pulp Fiction',
  'overview': "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
  'popularity': 37.1431,
  'poster_path': '/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg',
  'release_date': '1994-09-10',
  'softcore': False,
  'video': False,
  'vote_average': 8.481,
  'vote_count': 30409},
 {'adult': False,
  'backdrop_path': '/mMtUybQ6hL24FXo0F3Z4j2KG7kZ.jpg',
  'genre_ids': [16, 10749, 18],
  'id': 372058,
  'title': 'Your Name.',
  'original_language': 'ja',
  'original_title': '君の名は。',
  'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
  'popularity': 24.3043,
  'poster_path': '/q719jXXEzOoYaps6babgKnONONX.jpg',
  'release_date': '2016-07-01',
  'softcore': False,
  'video': False,
  'vote_average': 8.481,
  'vote_count': 12685}]

In [9]:
pd.DataFrame(response.json()['results'])

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/iCML6fBe3X0y06P33bM7dyYXPKZ.jpg,"[35, 10749]",1632181,Accidental Partners,es,Socias por accidente,Two women discover they were both scammed by t...,21.6787,/sr1Yoj6XLPTWYcbDoBy67xivW4I.jpg,2026-03-12,False,False,9.066,304
1,False,/zMwhWailP1WY7sb6AoE6b8ugoy.jpg,"[12, 16, 10751, 14]",1007757,Swapped,en,Swapped,"A small woodland creature and a majestic bird,...",88.4108,/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg,2026-05-01,False,False,8.915,1923
2,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,The Shawshank Redemption,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,167.4100,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,False,False,8.725,30748
3,False,/ufSwlnECLoUbBjPrFqEQcWBzHwc.jpg,"[10402, 18]",936075,Michael,en,Michael,"The story of Michael Jackson, one of the most ...",175.7718,/zm0KAbOjlt9eR5y7vDiL2dEOwMl.jpg,2026-04-22,False,False,8.701,3458
4,False,/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg,"[18, 80]",238,The Godfather,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",38.3895,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,False,False,8.687,23153
5,False,/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg,"[878, 12]",687163,Project Hail Mary,en,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,163.4379,/yihdXomYb5kTeSivtFndMy5iDmf.jpg,2026-03-15,False,False,8.670,5994
6,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[18, 80]",240,The Godfather Part II,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,33.3141,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,False,False,8.571,14037
7,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[18, 36, 10752]",424,Schindler's List,en,Schindler's List,The true story of how businessman Oskar Schind...,22.1871,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,False,False,8.570,17592
8,False,/qqHQsStV6exghCM7zbObuYBiYxw.jpg,[18],389,12 Angry Men,en,12 Angry Men,The defense and the prosecution have rested an...,22.4873,/zhG3vKWyDRaZYoaww1UVAi29T9h.jpg,1957-04-10,False,False,8.565,10110
9,False,/bVGHSe47W6oCQL1Q88pvRAet51A.jpg,"[18, 9648]",1330021,Remarkably Bright Creatures,en,Remarkably Bright Creatures,Through unlikely bonds formed during night shi...,22.6466,/9HcEqn3D4J6b2Z0jK54id9nA0fr.jpg,2026-05-07,False,False,8.551,722
10,False,/vpuPY4UziUCxv7gYYoaZQ3LX7to.jpg,"[28, 53]",1383731,Protector,en,Protector,Nikki's life is shattered when her daughter is...,19.0537,/icOZpnGuH9YrEaW3wrw5GJaXGih.jpg,2026-02-20,False,False,8.500,423
11,False,/dyJvKsNs2KP8qQnAXbRwDjblViy.jpg,"[16, 10751, 14]",129,Spirited Away,ja,千と千尋の神隠し,"A young girl, Chihiro, becomes trapped in a st...",36.5499,/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg,2001-07-20,False,False,8.535,18526
12,False,/dqK9Hag1054tghRQSqLSfrkvQnA.jpg,"[28, 80, 53]",155,The Dark Knight,en,The Dark Knight,Batman raises the stakes in his war on crime. ...,42.6872,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,2008-07-16,False,False,8.532,36080
13,False,/84beTJf26mfhoasUlKSOiNSutyS.jpg,"[35, 18, 10749]",19404,Dilwale Dulhania Le Jayenge,hi,दिलवाले दुल्हनिया ले जायेंगे,"Raj is a rich, carefree, happy-go-lucky second...",12.2635,/tFbfCkS7q6g96wVoAu8kyr93iPm.jpg,1995-10-20,False,False,8.510,4600
14,False,/b6HWTOxn1xevvyHU2K9ICvaRU6g.jpg,"[14, 18, 80]",497,The Green Mile,en,The Green Mile,A supernatural tale set on death row in a Sout...,26.8308,/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg,1999-12-10,False,False,8.506,19422
15,False,/xyWKrni8WrYzqn7ztvI5nIY0h62.jpg,"[35, 10749]",1181678,¿Quieres ser mi hijo?,en,¿Quieres ser mi hijo?,"Lu, a conformist woman in her forties, learns ...",9.8430,/6PQJsmuvSMZQMmlJfTpjIkrizUh.jpg,2023-09-21,False,False,8.501,356
16,False,/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg,"[12, 14, 28]",122,The Lord of the Rings: The Return of the King,en,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,36.8675,/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg,2003-12-17,False,False,8.500,26827
17,False,/wCuUKiRaz0wEESsYqmQy005xvTE.jpg,"[35, 53, 18]",496243,Parasite,ko,기생충,"All unemployed, Ki-taek's family takes peculia...",28.2785,/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg,2019-05-30,False,False,8.492,20854
18,False,/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg,"[53, 80, 35]",680,Pulp Fiction,en,Pulp Fiction,"A burger-loving hit man, his philosophical par...",37.1431,/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg,1994-09-10,False,False,8.481,30409
19,False,/mMtUybQ6hL24FXo0F3Z4j2KG7kZ.jpg,"[16, 10749, 18]",372058,Your Name.,ja,君の名は。,High schoolers Mitsuha and Taki are complete s...,24.3043,/q719jXXEzOoYaps6babgKnONONX.jpg,2016-07-01,False,False,8.481,12685

In [19]:
#Now extract the important thing
temp_df=pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','overview','popularity','vote_average','vote_count']]
temp_df

,id,title,overview,release_date,overview,popularity,vote_average,vote_count
0,1632181,Accidental Partners,Two women discover they were both scammed by t...,2026-03-12,Two women discover they were both scammed by t...,21.6787,9.066,304
1,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,"A small woodland creature and a majestic bird,...",88.4108,8.915,1923
2,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,Imprisoned in the 1940s for the double murder ...,167.4100,8.725,30748
3,936075,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,"The story of Michael Jackson, one of the most ...",175.7718,8.701,3458
4,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,"Spanning the years 1945 to 1955, a chronicle o...",38.3895,8.687,23153
5,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,Science teacher Ryland Grace wakes up on a spa...,163.4379,8.670,5994
6,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,In the continuing saga of the Corleone crime f...,33.3141,8.571,14037
7,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,The true story of how businessman Oskar Schind...,22.1871,8.570,17592
8,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,The defense and the prosecution have rested an...,22.4873,8.565,10110
9,1330021,Remarkably Bright Creatures,Through unlikely bonds formed during night shi...,2026-05-07,Through unlikely bonds formed during night shi...,22.6466,8.551,722
10,1383731,Protector,Nikki's life is shattered when her daughter is...,2026-02-20,Nikki's life is shattered when her daughter is...,19.0537,8.500,423
11,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,"A young girl, Chihiro, becomes trapped in a st...",36.5499,8.535,18526
12,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,2008-07-16,Batman raises the stakes in his war on crime. ...,42.6872,8.532,36080
13,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,"Raj is a rich, carefree, happy-go-lucky second...",12.2635,8.510,4600
14,497,The Green Mile,A supernatural tale set on death row in a Sout...,1999-12-10,A supernatural tale set on death row in a Sout...,26.8308,8.506,19422
15,1181678,¿Quieres ser mi hijo?,"Lu, a conformist woman in her forties, learns ...",2023-09-21,"Lu, a conformist woman in her forties, learns ...",9.8430,8.501,356
16,122,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,2003-12-17,As armies mass for a final battle that will de...,36.8675,8.500,26827
17,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,"All unemployed, Ki-taek's family takes peculia...",28.2785,8.492,20854
18,680,Pulp Fiction,"A burger-loving hit man, his philosophical par...",1994-09-10,"A burger-loving hit man, his philosophical par...",37.1431,8.481,30409
19,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,2016-07-01,High schoolers Mitsuha and Taki are complete s...,24.3043,8.481,12685

In [21]:
df=pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [26]:
for i in range(1,501):
  response=requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=fab97f3edabaf2d64d83d65ef5dc35e0&language=en-US&page={}'.format(i))
  temp_df=pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','overview','popularity','vote_average','vote_count']]
  df = pd.concat([df, temp_df], ignore_index=True)

In [27]:
df

,id,title,overview,release_date,overview,popularity,vote_average,vote_count
0,1632181,Accidental Partners,Two women discover they were both scammed by t...,2026-03-12,Two women discover they were both scammed by t...,21.6787,9.066,304
1,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,"A small woodland creature and a majestic bird,...",88.4108,8.915,1923
2,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,Imprisoned in the 1940s for the double murder ...,167.4100,8.725,30748
3,936075,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,"The story of Michael Jackson, one of the most ...",175.7718,8.701,3458
4,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,"Spanning the years 1945 to 1955, a chronicle o...",38.3895,8.687,23153
...,...,...,...,...,...,...,...,...
29995,13572,Twisted,Recently promoted and transferred to the homic...,2004-02-27,Recently promoted and transferred to the homic...,2.2132,5.587,613
29996,703745,Deep Blue Sea 3,Dr. Emma Collins and her team are spending the...,2020-08-25,Dr. Emma Collins and her team are spending the...,3.1596,5.586,355
29997,288171,Blue Mountain State: The Rise of Thadland,With Blue Mountain State football star Thad Ca...,2016-02-02,With Blue Mountain State football star Thad Ca...,1.2563,5.586,320
29998,46837,Kaboom,"Smith, a typical young college student who lik...",2010-10-06,"Smith, a typical young college student who lik...",2.4182,5.600,360
29999,382511,Penny Pincher!,François Gautier is stingy! Saving puts the jo...,2016-09-28,François Gautier is stingy! Saving puts the jo...,2.5628,5.600,958

In [28]:
df.shape

(30000, 8)

In [29]:
df.to_csv('movies.csv')